amitproj/urls.py
# when u use class ab iski wjha se equest aati jati rhegi class base hain na to usse request ke rup pr convert kr dega

from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ratings', include('star_ratings.urls', namespace='ratings')),
    path('',include('music.controller')),
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
urlpatterns+=static(settings.STATIC_URL,document_root=settings.STATIC_ROOT)

music/models.py
from code import interact
from distutils import core
from email.headerregistry import Address
from tkinter import CASCADE
from typing import cast
from django.db import models
from django.urls import reverse
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
#always mak get absolute url for update and add album for reverse
class album(models.Model):
    title=models.CharField(max_length=100,help_text='album tile')
    artist=models.CharField(max_length=100)
    genre=models.CharField(max_length=100)
    release=models.DateField(max_length=100)
    image=models.FileField(validators=[FileExtensionValidator(['jpg','png','jpeg'],'allow.images')])


    def __str__(self):
        return f"album{self.title} artist{self.artist} genre{self.genre} release{self.release}"

    def get_absolute_url(self):
        return reverse('music:home')    


class song(models.Model):
    al_id=models.ForeignKey(album,on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    artist=models.CharField(max_length=50)
    genre=models.CharField(max_length=50)
    lyricist=models.CharField(max_length=50)
    file=models.FileField(validators=[FileExtensionValidator(['mp3','aac','amr','wav'],'allow.mp3')])


    def __str__(self):
        return f"{self.title}artist{self.artist}genre{self.genre}lyricist{self.lyricist}file{self.file}"

    def get_absolute_url(self):
        return reverse('music:detail',kwargs={'pk':self.al_id.id})   

class profile(models.Model):
    u_id=models.OneToOneField(User,on_delete=models.CASCADE)
    image=models.FileField(validators=[FileExtensionValidator(['jpg','png','jpeg'])])
    address=models.TextField(max_length=100)
    intrest=models.CharField(max_length=50)
    dob=models.DateField()

music/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.forms import fields
from django.forms.widgets import PasswordInput
from django.contrib.auth import authenticate # for check from database



class Register(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput)
    Retype_password=forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model=User
        fields=['username','first_name','last_name','email']

    def clean(self):
        super().clean() ###for all the constructor allready in form inherit the feature
        p=self.cleaned_data.get('password')
        p1=self.cleaned_data.get('Retype_password')
        if p!=p1:
            raise forms.ValidationError("both passwords did not match")    




class logform(forms.Form):
    username=forms.CharField(max_length=100,help_text="user name")
    password=forms.CharField(max_length=20,widget=forms.PasswordInput)
    def clean(self):
        u=self.cleaned_data.get("username")
        p=self.cleaned_data.get("password")
        ur=authenticate(username=u,password=p)
        if ur==None:
            raise ValidationError("user does not exist")

        

                

music/controller.py
from unicodedata import name
from django.urls import path
from music.forms import Register
from music.views import Home,Dts,signup,signin,AddAlbum,upalbum,Delalbum,Addsong
from . import views
app_name='music'

urlpatterns = [
    path('',Home.as_view(),name='home'),
    path("<int:pk>",Dts.as_view(),name='detail'),
    path("signup",signup.as_view(),name='Register'),
    path("signin",signin.as_view(),name='login'),
    path("album/uploadalbum",AddAlbum.as_view(),name='addalbum'),
    path("album/update/<int:pk>/",upalbum.as_view(),name='upalbum'),
    path("album/delete/<int:pk>/",Delalbum.as_view(),name='delalbum'),
    path("album/song/add/<int:pk>/",Addsong.as_view(),name='addsong'),
    path("album/song/update/<int:pk>/",views.upsong.as_view(),name='upsong'),
    path("album/song/delete/<int:pk>/",views.delsong.as_view(),name='delsong'),
    path("signout",views.signout,name='logout'),
    path('user/addprofile',views.AddProfile.as_view(),name='addprofile'),
    path('user/profile',views.show_profile,name='profile'),

]

music/views.py
#now join models with view
from django.db.models import fields
from django.http.response import Http404
from django.shortcuts import redirect, render,get_object_or_404
from django.http import HttpResponse,Http404, request
from django.urls.base import reverse_lazy
from .forms import Register,logform
from .models import album,song,profile
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.views.generic import ListView,DetailView,View,CreateView,UpdateView,DeleteView
# Create your views here.
#def home(request):
    #return HttpResponse('<h1>site under construction</h1>')

# def home(request):
#     return  render (request,'music/home.html')
"""def home(request):
    a=album.objects.all()
    str=''
    for i in a:
        str=str+"<h1>"+i.title+"</h1>"
    print(str)
    return HttpResponse(str)    

def home(request):
    a=album.objects.all()
    return render(request,"music\home.html",{'data':a})"""

class Home(ListView):
    #kis html par bhejna ha 
    template_name="music\home.html"
    #kis nam se bhjna ha
    context_object_name='data'
    #kya bhjna ha 
    def get_queryset(self):
        return {'car':enumerate(album.objects.all()),'dt':album.objects.all()}

# def dts(request,val):
#     # try:
#     #     a=album.objects.get(id=val)
#     # except:
#     #     raise Http404("matching querry does not exist")
#     a=get_object_or_404(album,id=val)
#     if a.song_set.all():
#         st=''
#         for i in a.song_set.all():
#             st+="<h1>"+i.title+"</h1>"
#         return HttpResponse(st) 
#     else:
#         return HttpResponse("<h1>no song to display</h1>")
#  # print(data,p)      
    
class Dts(DetailView):
    model=album
    template_name="music/song.html"
    context_object_name="data"



# def signup(request):
#     f=Register(request.POST or None)
#     if f.is_valid(): #ISVALID HERE THE CALLING OF CLEAN
    #     data=f.save(commit=False)
    #     p=f.cleaned_data.get('password')
    #     data.set_password(p)
    #     data.save()
    #     return HttpResponse("user added")
    # return render(request,'music/signup.html',{"data":f})
class signup(View):
    def get(self,request):
        f=Register(None)
        return render(request,'music/signup.html',{"data":f})
    def post(self,request):
        f=Register(request.POST)
        if f.is_valid():
            data=f.save(commit=False)
            p=f.cleaned_data.get('password')
            data.set_password(p)
            data.save()
            return redirect('music:home')
        return render(request,'music/signup.html',{"data":f})
            


'''def signin(request):
    f=logform(request.POST or None)
    if f.is_valid():
        u=f.cleaned_data.get('username')
        return HttpResponse(f"user:{u} logged in successfully")
    return render(request,"music/login.html",{'data':f})'''

class signin(View):
    def get(self,request):
        f=logform(None)
        return render(request,"music/login.html",{'data':f})
    def post(self,request):
        f=logform(request.POST)
        if f.is_valid():
             u=f.cleaned_data.get('username')
             p=f.cleaned_data.get('password')
             ur=authenticate(username=u,password=p)
             nxt=request.GET.get('next')
             if ur:
                 login(request,ur)
                 if nxt:
                     return redirect(nxt)
             return redirect('music:home') #home ka url load krwane ke liye return mein
        return render(request,"music/login.html",{'data':f})
   

def signout(request):
    logout(request)
    return redirect('music:home')
    
class AddAlbum(LoginRequiredMixin,CreateView):
    login_url='music:login'
    model=album
    fields=['title','artist','genre','release','image']
    template_name='music/addalbum.html'
                           

class upalbum(LoginRequiredMixin,UpdateView):
    login_url='music:login'
    model=album
    fields=['title','artist','genre','release','image']
    template_name='music/upalbum.html'

class Delalbum(LoginRequiredMixin,DeleteView):
    login_url='music:login'
    model=album
    success_url=reverse_lazy('music:home')
    template_name='music/delalbum.html'
    context_object_name='data'    


class Addsong(LoginRequiredMixin,CreateView):
    login_url='music:login'
    model=song
    fields=['title','artist','genre','lyricist','file']
    template_name='music/addalbum.html'

    def form_valid(self, form):
        p=self.kwargs.get('pk')
        a=album.objects.get(id=p)
        form.instance.al_id=a
        return super().form_valid(form)



class upsong(UpdateView):
    model=song
    fields=['title','artist','genre','lyricist','file']
    template_name='music/addalbum.html'            

class delsong(DeleteView):
    model=song
    success_url=reverse_lazy('music:home')
    template_name='music/delalbum.html'
    context_object_name='data'  


class AddProfile(LoginRequiredMixin,CreateView):
    login_url='music:login'
    model=profile
    fields=['image','address','intrest','dob']
    template_name='music/addalbum.html'

    def form_valid(self, form):
        p=self.request.user.id
        a=User.objects.get(pk=p)
        form.instance.u_id=a
        return super().form_valid(form)    

def show_profile(request):
    return render(request,'music/profile_page.html')

music/templates/music/addalbum.html
{%extends 'music/master.html'%}
{%block title%}add album page{%endblock%}
{%block body%}
<form method="post" enctype="multipart/form-data">
{%csrf_token%}
<table>
{{form.as_table}}
</table>
<input type="submit" value="login">
</form>
{%endblock%}

music/templates/music/delalbum.html
{%extends 'music/master.html'%}
{%block title%}delalbum page{%endblock%}
{%block body%}
<form method="post" enctype="multipart/form-data">
{%csrf_token%}
<div class="container mt-4 ml-10 mr-4">
    <div class="row">
      <div class="col">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{data.image.url}}" alt="Card image cap" height="100px">
        <div class="card-body">
          <h5 class="card-title">{{data.title}}</h5>
          <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        </div>
      </div>
      </div>
    </div>
  </div>
<input type="submit" value="submit">
</form>
{%endblock%}

music/templates/music/home.html
{%extends 'music/master.html'%}
{%block title%}home{%endblock%}
{%block body%}
<div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
  <div class="carousel-inner">
    {%for i,j in data.car%}
    {%if not i%}
    <div class="carousel-item active">
      <img class="d-block w-100" src="{{j.image.url}}" alt="First slide" height="200px" width='1000px'>
    </div>
    {%else%}
    <div class="carousel-item">
      <img class="d-block w-100" src="{{j.image.url}}" height="200px" width="1000px">
    </div>
    {%endif%}
    {%endfor%}
  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
{% load ratings %}
<div class="container mt-4 ml-10 mr-4">
  <div class="row">
    {%for j in data.dt%}
    <div class="col">
    <div class="card" style="width: 18rem;">
      <img class="card-img-top" src="{{j.image.url}}" alt="Card image cap" height="100px">
      <div class="card-body">
        <h5 class="card-title">{{j.title}}</h5>
        <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
        <a href="{{j.id}}" class="btn btn-primary">view songs</a>
        <p>{% ratings j  %}</p>
      </div>
    </div>
    </div>
    {%endfor%}
  </div>
</div>
{%endblock%}

music/templates/music/login.html
{%extends 'music/master.html'%}
{%block title%}login page{%endblock%}
{%block body%}
<form method="post" enctype="multipart/form-data">
{%csrf_token%}
<table>
{{data.as_table}}
</table>
<input type="submit" value="login">
</form>
{%endblock%}

music/templates/music/master.html
<!doctype html>
<html>
<head>
    {% load bootstrap4 %}
    {%bootstrap_css%}
    {%bootstrap_javascript jquery="full"%}
    {% load static %}
    <link rel="stylesheet" href="{% static 'star-ratings/css/star-ratings.css' %}">
    <script type="text/javascript" src="{% static 'star-ratings/js/dist/star-ratings.min.js' %}"></script>
    <link rel="stylesheet"  href="{% static 'music/style.css' %}"></link>
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light " style="background-color:#4287f5;">
        <a class="navbar-brand" href="{% url 'music:home' %}">DHUN</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'music:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>
            {% if request.user.is_authenticated %}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'music:addalbum' %}">Album</a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{request.user.username}}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                {%if request.user.profile%}
                <a class="dropdown-item" href="{% url 'music:profile'%}">profile</a>
                {%else%}
                <a class="dropdown-item" href="{% url 'music:addprofile'%}">Addprofile</a>
                {%endif%}
                <a class="dropdown-item" href="{% url 'music:logout' %}">logout</a>
            </li>
            {%else%}
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'music:login' %}">signin</a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{% url 'music:Register' %}">signup</a>
            </li>
            {% endif %}
          </ul>
          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
          </form>
        </div>
      </nav>
{%block body%}
{%endblock%}
</body>
</html>

music/templates/music/profile_page.html
{%extends 'music/master.html'%}
{%block title%}{{ request.user.username}}{%endblock%}
{% block body%}
<div class="page-content page-container" id="page-content">
    <div class="padding">
        <div class="row container d-flex justify-content-center">
            <div class="col-xl-6 col-md-12">
                <div class="card user-card-full">
                    <div class="row m-l-0 m-r-0">
                        <div class="col-sm-4 bg-c-lite-green user-profile">
                            <div class="card-block text-center text-white">
                                <div class="m-b-25"> <img src="{{request.user.profile.image.url}}" class="img-radius" alt="User-Profile-Image" width="150" height="200"> </div>
                                <h6 class="f-w-600">{{request.user.username}}</h6>
                                <p>{{request.user.first_name}}</p> <i class=" mdi mdi-square-edit-outline feather icon-edit m-t-10 f-16"></i>
                            </div>
                        </div>
                        <div class="col-sm-8">
                            <div class="card-block">
                                <h6 class="m-b-20 p-b-5 b-b-default f-w-600">Information</h6>
                                <div class="row">
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">Email</p>
                                        <h6 class="text-muted f-w-400">{{request.user.email}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">address</p>
                                        <h6 class="text-muted f-w-400">{{request.user.profile.address}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">DOB</p>
                                        <h6 class="text-muted f-w-400">{{request.user.profile.dob}}</h6>
                                    </div>
                                    <div class="col-sm-6">
                                        <p class="m-b-10 f-w-600">intrest</p>
                                        <h6 class="text-muted f-w-400">{{request.user.profile.intrest}}</h6>
                                    </div>
                                </div>
                                <ul class="social-link list-unstyled m-t-40 m-b-10">
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="facebook" data-abc="true"><i class="mdi mdi-facebook feather icon-facebook facebook" aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="twitter" data-abc="true"><i class="mdi mdi-twitter feather icon-twitter twitter" aria-hidden="true"></i></a></li>
                                    <li><a href="#!" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="instagram" data-abc="true"><i class="mdi mdi-instagram feather icon-instagram instagram" aria-hidden="true"></i></a></li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%} 

music/templates/music/signup.html
{%extends 'music/master.html'%}
{%block title%}signup page{%endblock%}
{%block body%}
<form method="post" enctype="multipart/form-data">
{%csrf_token%}
<table>
{{data.as_table}}
</table>
<input type="submit" value="submit">
</form>
{%endblock%}

music/templates/music/song.html
{%extends 'music/master.html'%}
{%block title%}{{data.title}}{%endblock%}
{%block body%}
{%load ratings%}
<div class="container mt-4 ml-10 mr-4">
    <div class="row">
      <div class="col">
      <div class="card" style="width: 18rem;">
        <img class="card-img-top" src="{{data.image.url}}" alt="Card image cap" height="100px">
        <div class="card-body">
          <h5 class="card-title">{{data.title}}</h5>
          <p><h6>{{data.artist}}{{data.release}}</h6></p>
          <a href="{%url 'music:addsong' data.id%}" class="btn btn-primary">add songs</a>
          <p>{% ratings data%}</p>
        </div>
      </div>
      </div>
<div class="col">      
{%if data.song_set.all%}
<table class="table table-bordered table-primary">
    <thead>
        <td>TITLE</td>
        <td>ARTIST</td>
        <td>GENRE</td>
        <td>LYRICIST</td>
        <td>ACTION</td>
        {%if request.user.is_authenticated%} <td>MODIFY</td>{% endif %}
        <td>RATING</td>
    </thead>
    {% load ratings%}}
{%for i in data.song_set.all%}
<tr>
    <td>{{i.title}}</td>
    <td>{{i.artist}}</td>
    <td>{{i.genre}}</td>
    <td>{{i.lyricist}}</td>
    <td><audio controls='controls'><source src="{{i.file.url}}" type="audio/mpeg"></audio></td>
    {%if request.user.is_authenticated %}
    <td>
      <p>
        <a href="{% url 'music:upsong' i.id%}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">up song</a>
        <a href="{% url 'music:delsong' i.id%}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">del song</a>
      </p>
    </td>
    {%endif%}
    <td>{%ratings i%}</td>
</tr>  

{%endfor%}

{%else%}
<h1>no song to display</h1>
{%endif%}
</div>
</div>
</div>
{%endblock%}

music/templates/music/upalbum.html
{%extends 'music/master.html'%}
{%block title%}upalbum page{%endblock%}
{%block body%}
<form method="post" enctype="multipart/form-data">
{%csrf_token%}
<table>
{{form.as_table}}
</table>
<input type="submit" value="submit">
</form>
{%endblock%}